spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:yongcoding
    username: sa
    password:
    driver-class-name: org.h2.Driver

# 1부터 파라미터를 시작할 수 있도록 함.
# 5개만 나옴
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5